# Generated by Django 5.0.2 on 2024-04-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_basemodel_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
